#!/bin/zsh -f
# -*- shell-script -*-
t=${0##*/}; TEST_NAME=$t[6,-1]   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && export builddir=$PWD

. ${builddir}/check-common.sh
ARGS='testarg1 testarg2'
debugged_script="${top_srcdir}/test/example/dbg-test2.sh"
(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

cat ${TEST_FILE} | sed -e "s:-x .*/data/setshow\.cmd .*/example/dbg-test2.sh:-x data/setshow.cmd example/dbg-test2.sh:" \
| sed -e 's:record the command history is .*:record the command history is: ' \
> ${TEST_FILTERED_FILE}
check_output $TEST_FILTERED_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
